services:
  web:
    build: .
    ports:
      - "9001:5000"
    restart: unless-stopped
    env_file:
      - path: .env.example
        required: false
      - path: .env
        required: false